name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create remote URL file
        run: echo "https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }}" > remote_url.txt

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: my-docker-image:${{ github.sha }}

      - name: Extract image information
        run: echo "ghcr.io/${{ github.repository }}/my-custom-image:latest" > docker_image.txt

      - name: Commit and push the changes
        run: |
          git remote set-url origin "$(cat remote_url.txt)"
          git add docker_image.txt
          git commit -m "Update Docker image info"
          git push origin HEAD:${{ github.ref }}
