name: Docker Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: my-docker-image:${{ github.sha }}

      - name: Extract image information
        run: echo "ghcr.io/${{ github.repository }}/my-custom-image:latest" > docker_image.txt

      - name: Commit and push the changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Docker image info"
          branch: ${{ github.ref }}
          files: |
            docker_image.txt
